### PR TITLE
Jekyll Site

### LINKED ISSUE #12: Jekyll site
I will create a Jekyll site

### PR DESCRIPTION
**Pull request by israelperezglez**
@calvellido @AntonioMateoGomez  could you review this PR please?

This closes #12

### CODE REVIEW

**Comment by pakoito** [comment]
🌊

**Comment by israelperezglez** [comment]
@AntonioMateoGomez @calvellido Can we merge this PR?

**Comment by calvellido** [comment]
I'm planning to have a look later today, if it can wait to then the better :slightly_smiling_face:

**Comment by juanpedromoreno** [comment]
@calvellido is this deployed to gh-pages? https://47deg.github.io/helios seems to be 404

**Comment by calvellido** [comment]
I did nothing to deploy it, so probably not unless someone else did it.

If we are planning to officially launch it and deploy I'd need admin privileges in this repo.

**Pull request merged**
