### PR TITLE
Format following Kotlin style guide

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Format following Kotlin style guide and some clean up (mostly delete redundant `:Unit`)

Sorry for the ton of changes

### CODE REVIEW

**Comment by raulraja** [comment]
I disagree with removing Unit in general. That is something I thing the guide gets wrong. Unit return types indicate at least a function is side effecting and leaving that to inference hides the nasty bits of uncontrolled effects.

**Comment by nomisRev** [comment]
Oh yes 2 space formatting 🎉

**Comment by AdrianRaFo** [comment]
@raulraja I agree with you but a method without a `=` or  `return` mark the explicit Unit as redundant an unnecessary. Let me see if I can change this or revert it and disable the inspection

**Comment by AdrianRaFo** [comment]
Could someone from @47deg/team-celulares give an extra review here?

**Comment by arturogutierrez** [comment]
Just one question. AFAIK, Kotlin Style guide uses +4 spaces as indent size and +8 as a continuation indent, so why are you using a 2 size here?

**Comment by nomisRev** [comment]
@arturogutierrez that is the style we use in Arrow as well.

It makes code more readable when writing nested lamdas.

(Closed PR by accident on phone.)

**Pull request merged**
