### PR TITLE
Update to arrow 0.7.2

### PR DESCRIPTION
**Pull request by nomisRev**
The project in a compile-able state.

Changes:
  * `@json` annotated data classes now require a `companion object`
  * Special cases had to be built into the `meta-compiler` [here](https://github.com/47deg/helios/compare/simon-arrow-0.7.2?expand=1#diff-475e471d42df1a19a7d3651bcd08aaaeR54)
  * Removed retrofit module because it relied on the implicit resolution. Retrofit relies on runtime reflection in order to work and there is no way to make it compile safe AFAIK.

TODO:
- [ ] Improve special cases in `meta-compiler`

What still needs to be done before alpha release?
  * Remove `arrow-optics` dependency from `core`?
  * Update `arrow-optics` API to be closer to Optics DSL and work together with the Optics DSL.

### CODE REVIEW

**Comment by nomisRev** [comment]
Something we could do for the time being where we don't have true typeclasses is adding most common special cases to `Encoder<A>` as follows:

```kotlin
interface Encoder<in A> {
    fun A.encode(): Json
    fun Iterable<A>.toJson(): JsArray = JsArray(map { it.encode() })
    fun Option<A>.toJson(): Json = fold({ JsNull }, { it.encode() })
    fun Try<A>.toJson(): Json = fold({ JsNull }, { it.encode() })
}
```

This way we could check if `F` of `Kind<F, A>` is in the list of known special cases and simply use `Encoder<A>` for it. And if it is not known add it as a parameter.

Example of the case where `Iterable`, `Try` and `Option` are known special cases:

```kotlin
@json data class Friend(val _id: String, val tags: List<String>)
@json data class SpecialFriend(val _id: String, val errorOrTags: Either<Error, List<String>>)

fun Friend.toJson(): Json = ...
fun SpecialFriend.toJson(ENA: Encoder<Either<Error, List<String>>>): Json = ...
```

Side-note: While I think this is a nice solution for `Encoder`, offering the functions in `Encoder` instead of keeping them in the `meta-compiler`, we cannot do this for `Decoder` and will have to build in the special cases there.

**Comment by AdrianRaFo** [comment]
@nomisRev Is this finished? How can we help?

**Comment by raulraja** [comment]
@nomisRev 
> I made an attempt to discover supertypes of params but failed..
This should be now possible with `arrow-meta` in a pretty straightforward way.
Let me know if I can help but it'd be something along the lines of:
```
param.type.asType().superTypes()
```
If you are in the context of a sub type of `MetaProcessor`

**Comment by nomisRev** [comment]
@AdrianRaFo @raulraja the problem lied with the meta compiler. More specifically when generating encoders/decoders for product types that depend on other encoders/decoders such as `List<String>` or `Option< List<String>>`.

```kotlin
@json data class Friend(val _id: String, val tags: List<String>)
@json data class SpecialFriend(val _id: String, val errorOrTags: Option< List<String>>)
```

I am unsure how to safely generate encoders for these product types.

Beside that this PR is ready IIRC.

**Comment by AdrianRaFo** [comment]
I created an issue for that https://github.com/47deg/helios/issues/24 so we can merge this

**Pull request merged**
