### PR TITLE
Create lazy instances for codecs

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Create lazy instances for all the possible encoders and decoders in order to improve the performance

### CODE REVIEW

**Comment by 47degdev** [comment]
***Hood benchmark comparison:***
:heavy_check_mark: `Decoding` (Threshold: 406.4875320958234)

Benchmark | Value
|--|--|
master_benchmark | 10322.555329007957
helios_benchmark | 10747.212496099823


:heavy_check_mark: `Decodingfromraw` (Threshold: 250.0)

Benchmark | Value
|--|--|
master_benchmark | 7062.545961111575
helios_benchmark | 7318.575844549667


:heavy_check_mark: `Parsing` (Threshold: 250.0)

Benchmark | Value
|--|--|
master_benchmark | 20844.371140100884
helios_benchmark | 21337.161212228973

**Comment by pakoito** [comment]
You're replacing one object allocation with one object allocation + some extra code. There are no such wins when using `by lazy`. In memory it's an object with an invoke property that's called every time the value is accessed.

**Comment by AdrianRaFo** [comment]
But the lazy should create just one object the first time is used, isn't it? using fun we were creating one object each time

**Comment by nomisRev** [comment]
Yes, but lazy val does 2 initializations while `val` just does one 1. Given that these encoders are very light to initialize it makes no sense to make them lazy.

It uses locks and synchronization so potentially even slower than just `val`. [reference](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/src/kotlin/util/LazyJVM.kt#L55)

**Comment by AdrianRaFo** [comment]
Ok then, I'll change them to regular vals

**Pull request merged**
